filebeat.inputs:

  - type: filestream
    id: springboot-logs

    enabled: true

    paths:
      - /var/log/springboot/app.log

    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          add_error_key: true

    fields:
      service: springBootDemo

    fields_under_root: true


output.logstash:

  hosts:
    - "logstash:5044"