netology.profile.dev=true

spring.application.name=springBootDemo

server.port=8080

logging.level.root=INFO
logging.level.ru.netology.springBootDemo=INFO

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true

management.metrics.tags.application=${spring.application.name}