input {
    beats {
        port => 5044
    }
}

filter {
    if [application] {
        mutate {
            add_field => {
                "service_name" => "%{application}"
            }
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "springboot-logs-%{+YYYY.MM.dd}"
    }

    stdout {
        codec => rubydebug
    }
}
