groups:
  - name: springBootDemo-alerts

    rules:
      - alert: HighJvmMemoryUsage

        expr: |
          (
            jvm_memory_used_bytes{area="heap"}
            /
            jvm_memory_max_bytes{area="heap"}
          ) * 100 > 70

        for: 10s

        labels:
          severity: warning

        annotations:
          summary: "High JVM memory usage"
          description: "JVM heap memory usage is above 70% for more than 10 seconds."